export const START_ROM_LOAD = 'START_ROM_LOAD';
export const FINISH_ROM_LOAD = 'FINISH_ROM_LOAD';
export const SET_EMULATOR_RUNNING = 'SET_EMULATOR_RUNNING';
export const SET_EMULATOR_SUSPENDED = 'SET_EMULATOR_SUSPENDED';
export const SET_EMULATOR_ERROR = 'SET_EMULATOR_ERROR';
export const CLEAR_EMULATOR_ERROR = 'CLEAR_EMULATOR_ERROR';
