export const START_ROM_LOAD = 'START_ROM_LOAD';
export const FINISH_ROM_LOAD = 'FINISH_ROM_LOAD';
export const CLEAR_ROM_LOAD_ERROR = 'CLEAR_ROM_LOAD_ERROR';
export const SET_EMULATOR_RUNNING = 'SET_EMULATOR_RUNNING';
export const SET_EMULATOR_SUSPENDED = 'SET_EMULATOR_SUSPENDED';
