export const SET_ACTIVE_SETTINGS_PANEL = 'SET_ACTIVE_SETTINGS_PANEL';
export const SET_SETTINGS_VALUES = 'SET_SETTINGS_VALUES';
export const LOCK_SETTINGS_RESET = 'LOCK_SETTINGS_RESET';
export const UNLOCK_SETTINGS_RESET = 'UNLOCK_SETTINGS_RESET';
