#!/bin/node

const fs = require('fs');
const path = require('path');

const executable = path.basename(process.argv[1]);
const inputFile = process.argv[2];
const outputFile = process.argv[3];
const print = console.log;

if (!inputFile) {
  print('Usage: %s input-file [output-file]', executable);
  print('Converts palette in .pal format to base64 string wrapped in ES6 module.');
  process.exit(0);
}

const input = fs.readFileSync(inputFile);
const output = outputFile ? fs.createWriteStream(outputFile) : process.stdout;

output.write('// Converted from ' + path.basename(inputFile) + ' using ' + executable + '\n');
output.write('export default \'');
output.write(input.toString('base64'));
output.write('\';\n');

if (output !== process.stdout) {
  output.end();
}
